name: Lingo.dev i18n

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "dependabot-**"


permissions:
  contents: write
  pull-requests: write

jobs:
  i18n:
    name: Run i18n
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - uses: actions/checkout@v4
      - uses: lingodotdev/lingo.dev@gitlab
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: true
          commit-message: "this is i18n"
          working-directory: ./my-app

