name: Replexica i18n

on:
  push:
    branches:
      - main
  pull_request_target:
    branches-ignore:
      - "dependabot-**"


permissions:
  contents: write
  pull-requests: write

jobs:
  i18n:
    name: Run i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: replexica/replexica@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: false

