name: Replexica i18n

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "dependabot-**"


permissions:
  contents: write
  pull-requests: write

jobs:
  i18n:
    name: Run i18n
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - uses: actions/checkout@v4
      - uses: replexica/replexica@working-dir
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: false
          #working-directory: ./my-app

