name: Replexica i18n

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "dependabot-**"


permissions:
  contents: write
  pull-requests: write

jobs:
  i18n:
    name: Run i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with: 
      #     limit-access-to-actor: true
      - uses: replexica/replexica@configure-git
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.REPLEXICA_API_KEY }}
          pull-request: false

